# Generated by Django 5.1.7 on 2025-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='masterClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('price', models.TextField()),
                ('maxAttendees', models.IntegerField()),
                ('participants', models.IntegerField()),
                ('createdUser', models.TextField()),
            ],
        ),
    ]
